### ISSUE TITLE
Navbar - render plot

### ISSUE THREAD

**Issue by JohnCoene** [JohnCoene/shinybulma#5]
Navbar toggling of hide/show elements does "work" but does not trigger shiny render/reactives.

**Comment by JohnCoene** [comment]
Current "fix" is  to initialise all elements as `display: block` then hide/show with JavaScript => means all elements flash on screen for a fraction of second. Not ideal, at all.

**Comment by JohnCoene** [comment]
Fixed for good I hope.

**Explanation** 

Shiny depends on jquery, `shinybulma` was re-importing the library, causing clashes. I simply removed jquery ui, nav works fine and `bulmaNav` are now initialised as `display:none;` like they should.

**Comment by DivadNojnarg** [comment]
Hi John. Thanks for this fix 😃
